[package]
name = "mqtt"
version.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
common = { path = "../common" }
machine-uid = "0.5"
mockall = "0.15.0"
rumqttc = { version = "0.25.1", features = ["use-rustls"] }
serde = "1.0.228"
serde_json = "1.0.150"
thiserror = "2.0"

